config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins

  root "books#index"

  resources :books do
    resources :votes
    resources :comments, only: [:create, :destroy]
  end


  resources :categories
  resources :authors

  resources :categories, only: [:show, :index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
	validates :firstName, :lastName, presence: true
	has_many :books, dependent: :destroy
	has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category
  has_many :comments, dependent: :destroy
  belongs_to :author
  has_many :status
  has_many :votes,	dependent: :destroy
  has_many :votes, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, uniqueness: true
  has_many :books
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true
  belongs_to :book
  belongs_to :user, optional: true
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :users
  has_many :books

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
end

app/models/vote.rb
class Vote < ApplicationRecord
	belongs_to :book
	belongs_to :user



  	validates :user_id, uniqueness: {scope: :book_id}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_author, only: [:show, :update, :edit, :destroy]



  def new
    @author = Author.new
  end

  def index
    @author = Author.all
  end

  def show

  end

  def create

    @author = Author.new(author_params)

    if @author.save
      flash[:success] = 'Islem basariyla tamamlandi'
      redirect_to author_path(@author)
    else
      render :new
    end
  end

  def edit
  end

  def update

    if @author.update(idea_params)
      redirect_to author_path(@author)
    else
      load_form_data
      render :edit
    end

  end

  def destroy
    @author.destroy
    redirect_to authors_path, notice: "Idea was deleted"
  end

  private

  def set_author
    @author = Author.find(params[:id])
  end

  def author_params
    params.require(:author).permit(:fistName, :description, :lastName)
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_book, only: [:show, :destroy]


  def index
   @books= Book.all
  end

  def new
    @book=Book.new
    get_authors_and_categories

  end

  def show
    @vote = @book.votes.build
  end

  def create

    @book=Book.new(book_params)
    if @book.save
      flash[:success] = 'Islem basariyla tamamlandi'
      redirect_to books_path
    else
      get_authors_and_categories
      render :new
    end

  end

 # def destroy
  #  @book.destroy
   # redirect_to books_path, notice: "Book was deleted"
  #end

  private

  def book_params
    params.require(:book).permit(:name,:author_id,:category_id)
  end

  def get_authors_and_categories
    @authors = Author.all.collect {|c| [c.firstName, c.id ] }
    @categories = Category.all.collect {|c| [c.name, c.id ] }
  end

  def set_book
    @book = Book.find(params[:id])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :authenticate_admin!, [:show, :new, :destroy]
	before_action :set_category, only: [:show, :destroy]
	before_action :authorize_admin!, only: [:new, :create, :destroy]


    def new
	  @category = Category.new
	  load_categories
    end

    def index
      @categories = Category.all
    end

    def show
    end

	def create 

		@category = Category.new(category_params)
		if @category.save
			flash[:success] = 'İşlem başarıyla tamamlandı'
			redirect_to category_path(@category)
		else
			load_categories
			render :new
		end
	end

    def destroy
    	@category.destroy
    	redirect_to categories_path
    end


  private

    def authorize_admin!
      redirect_to root_path, notice: "Not authorized" unless @book.admin_id == current_admin.id
    end


	def load_categories
		@categories = Category.all.collect {|c| [c.name, c.id]}
	end

	def set_category
		@category = Category.find(params[:id])
	end

	def category_params
		params.require(:category).permit(:name)
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_book
  before_action :set_comment, only: [:destroy]
  before_action :authorize_user!, only: [:destroy]

	  def create
      @comment = @book.comments.new(comment_params)
      @comment.user=current_user

      if @comment.save!
        redirect_to @book, notice: "Comment was saved"
      else
        redirect_to @book, notice: "Comment couldn't saved"
      end
    end

    def destroy
      @comment.destroy
      redirect_to @book, notice: "Comment was deleted"
    end


    private

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def authorize_user!
    redirect_to @book, notice: "Not authorized" unless @comment.user_id == current_user.id
  end

    def comment_params
      params.require(:comment).permit(:body)
    end

    def set_book
      @book = Book.find(params[:book_id])
    end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_book
	before_action :set_vote , only: [:update]
	before_action :authorize_user!, only: [:update]
	

	def create 
		@vote = @book.votes.new
		@vote.rating = params[:vote][:rating]
		@vote.user = current_user
		if @vote.save
			redirect_to @book, notice: "Vote saved."
		else 
			redirect_to @book, notice: "Problem occured during saving vote."	
		end
	end

	def update
    if @vote.update(rating: params[:vote][:rating])
      redirect_to @idea, notice: "Vote was saved."
    else
      redirect_to @idea, notice: "Vote is not valid."
    end
  end


	private

		def vote_params
			params.require(:vote).permit(:rating)
		end

		def set_vote
			@vote = Vote.find(params[:id])
		end

		def set_book
			@book = Book.find(params[:book_id])
		end

		def authorize_user!
    		redirect_to @book, notice: "Not authorized" unless @book.user_id == current_user.id
  		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/application/_flash.html.erb
<% if !flash.empty? %>
  <div id="flash">
    <% flash.keys.each do |k| %>
      <div class="alert alert-warning" role="alert">
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <span class="sr-only">Error:</span>
        <%= flash[k] %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/authors/_form.html.erb
<%= form_for @author do |f| %>

  <%= f.label :firstName %>
  <%= f.text_field :firstName, placeholder: 'firstName', class: "form-control input-sm" %><br>
  <br>
    <%= f.label :lastName %>
    <%= f.text_field :lastName, placeholder: 'lastName', class: "form-control input-sm" %><br>
    <br>
  <%= f.label :description %>
  <br>
  <%= f.text_area :description, placeholder: "description", rows: 10 %><br>
  <br>
  <br>



   <br />
   <br />
   <br />

  <%= f.submit 'Gonder' %>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing <%= @author.title %></h1>

<% if @author.errors.any? %>
  <h3>
    <%= @author.errors.full_messages.join(", ") %>
  </h3>
<% end %>

<%= render partial: "form" %>

app/views/authors/index.html.erb
<% @author.each do |author| %>
	<%= link_to author.firstName + " " + author.lastName , author_path(author) %><br>
<% end %>
<br>
<br>
<br>
<br>
<%= link_to "Add new Author", new_author_path()%>

app/views/authors/new.html.erb
<h1>Create a new Idea</h1>

<% if @author.errors.any? %>
  <h3>
    <%= @author.errors.full_messages.join(", ") %>
  </h3>
<% end %>

<%= render "form" %>

app/views/authors/show.html.erb
<h2>Display Author</h2><br /><br />

<b>Title:  </b><%= @author.firstName %><br />
<b>Description:  </b><%= @author.description %><br />
<b>Category: </b><%= @author.lastName%><br /><br />

<br /><br /><br />

<br/><br/>

<br/><br/>
<%= link_to "Back to main page", books_path %>
  <br/>
<%= link_to "Back to Authors Page", authors_path %>

<% if current_user.present? %>
  <br/>
  <%= link_to "Edit Author", edit_author_path(@author) %>
  <br/>

<% end %>

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: 'Book Name', class: "form-control input-sm" %><br>
    <br>
    <%= f.select :author_id, @authors %>
    <%= f.select :category_id, @categories %>
    <%= f.submit 'Gonder' %>
<% end %>

app/views/books/edit.html.erb
<%= render "form" %>

app/views/books/index.html.erb
<% @books.each do |book| %>
<b>Name:</b><%=link_to book.name, book %><br/>
<b>Description:</b> <%= book.description %><br>
<b>Category:</b> <%= book.category.name %>

<br/><br><br>

<% end %>

<br><br><br><br><br><br><br><br><br><br>

<%= link_to "Add new Book", new_book_path()%>

app/views/books/new.html.erb
<%= render "form" %>

<% if @book.errors.any? %>
    <h3>
      <%= @book.errors.full_messages.join(", ") %>
    </h3>
<% end %>

app/views/books/show.html.erb
<%= @book.name %><br/>
<%= @book.pages %><br/>
<%= @book.description %><br/><br><br>




<%= render "/comments/comment_list" %>
<%= render "/comments/form" %>
<%= render "/votes/form" %>

<br><br>
<% @book.votes.each do |u| %>
    <%= u.rating %>
<% end %>

app/views/categories/index.html.erb
<h1>Listing Categories</h1>

<% @categories.each do |c| %>
  <%= link_to c.name, category_path(c) %><br />
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<% @category.books.each do |book| %>
  <b>Book Title </b>
  <%= link_to book.name, book_path(book) %>
<% end %>

app/views/comments/_comment_list.html.erb
   <% @book.comments.each do |comment| %>
   
    <small><%= current_user.email %> says:</small>
      <p>
        <%= comment.body %>
        <% if current_user.present? && comment.user_id == current_user.id %>
          <small><%= link_to "Delete", book_comment_path(@book, comment), method: :delete %></small>
        <% end %>
      </p>
    <% end %>

app/views/comments/_form.html.erb
Send a new comment

 	<%= form_for [@book, @book.comments.build] do |f| %>
        <%= f.text_area :body, rows: 5 %><br>
        <%= f.submit 'Send' %>
    <% end %>

app/views/votes/_form.html.erb
<% if current_user.present? %>
  <%= form_for [@book, @book.votes.build] do |f| %>
    <% 5.times do |i| %>
      <%= f.radio_button :rating, i+1 %>
      <% (i+1).times do %>
        <i class='fa fa-star'></i>
      <% end %>
    <% end %>

    <%= f.submit "Vote", class: "btn btn-sm btn-primary" %>
  <% end %>
 <% end %>

 